server:
  port: 8128

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://eureka.default.svc.cluster.local:8761/eureka/  
       defaultZone: http://localhost:8761/eureka/
       #defaultZone: http://172.18.173.76:8761/eureka/
       
druid:
#  url: jdbc:mysql://127.0.0.1:3306/sc_ucp?useUnicode=true&characterEncoding=utf-8
  url: jdbc:mysql://172.18.173.76:3306/servicecloud_ucp?useUnicode=true&characterEncoding=utf-8
  username: root
 # password: 123
  password: root
  useUnicode: true
  characterEncoding: UTF8
  useSSL: false
 
mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package: 
     org.springboot.sample.entity

spring:
  redis:
    #host: 127.0.0.1
    host: 172.18.173.79
    port: 6379
    
test:
  test1: 1